### ISSUE TITLE
Automatic pagination supported by official @typeform/api-client

### ISSUE THREAD

**Issue by mathio** [lirantal/typeform-client#34]
Hello @lirantal 

I'd like to let you know that [the official Typeform Node.js API client](https://github.com/Typeform/js-api-client) now supports automatic pagination [since October 2023](https://github.com/Typeform/js-api-client/commit/a8261009020fc87315d9542318451431d7e323c0).  It fetches at the rate of 2 requests per second to adhere to [rate limit policy](https://www.typeform.com/developers/get-started/#rate-limits).

If you would like to see any additional features implemented in the library, I am open to conversation. 

Cheers 👋

**Comment by lirantal** [comment]
Thanks! Appreciate the update
