### ISSUE TITLE
Add to the metadata the ability to show total respondents per question

### ISSUE THREAD

**Issue by lirantal** [lirantal/typeform-client#7]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Right now the metadata object doesn't include information about how many survey respondents were in each question.

**Comment by arszh** [comment]
Sorry, can you please tell more about this feature? Because I see 'field' has 'totalRespondents'.

**Comment by lirantal** [comment]
@arszh this was a while back but if I remember correctly, what we need is to collect the total respondents per question, not a global one. Perhaps it exists in this library, but not being utilized in https://github.com/lirantal/typeform-export-excel ?

**Comment by arszh** [comment]
@lirantal There are displayed only total respondents of each answer in excel file.  Maybe it relate to [typeform-export-excel](https://github.com/lirantal/typeform-export-excel)  to add "Total respondents" to metadata of  each question in excel file?

For example something like this: 
<img width="521" alt="Screen Shot 2019-12-01 at 14 31 24" src="https://user-images.githubusercontent.com/16872801/69914384-86ceef00-144c-11ea-9a72-65c2c51ea861.png">

**Comment by lirantal** [comment]
Yes that's what I think, but more than that - it is possible that the number of responses per question will be different because someone might have skipped it or it is part of a different questions group. That's why I think the functionality might be missing from typeform-client, because it's not the "total respondents" for the whole typeform, but rather per question which we don't have a field there today, right?

**Comment by arszh** [comment]
@lirantal  Question(`Field`) has `totalRespondents` , which is calculated  by real exist answers, not total respondents for whole form.

**Comment by lirantal** [comment]
Ahh gotcha. Maybe I did end up implementing it then, I can't honestly remember. Will close, thanks for looking into it!
